// The signing fixtures generated by the Hello Aigent backend must be verified
// by an independent test in the reference subscriber package.
// This uses the subscriber's own JCS + verify implementation (src/verify.ts),
// which shares no code with the server.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { jcsCanonicalize, verifyEnvelope } from '../src/verify.ts';

const dir = join(import.meta.dirname, 'fixtures', 'signing');
const read = (name: string) => readFile(join(dir, name), 'utf8');

test('subscriber JCS reproduces the backend canonical bytes', async () => {
  const unsigned = JSON.parse(await read('unsigned-envelope.json'));
  assert.equal(jcsCanonicalize(unsigned), await read('canonical-envelope.txt'));
});

test('subscriber verifies the backend-signed fixture envelope', async () => {
  const signed = JSON.parse(await read('signed-envelope.json'));
  const publicKey = (await read('public-key.txt')).trim();
  assert.equal(await verifyEnvelope(signed, publicKey), true);
});

test('subscriber rejects a tampered fixture envelope', async () => {
  const signed = JSON.parse(await read('signed-envelope.json'));
  const publicKey = (await read('public-key.txt')).trim();
  assert.equal(await verifyEnvelope({ ...signed, title: 'evil' }, publicKey), false);
  assert.equal(await verifyEnvelope({ ...signed, injected: 1 }, publicKey), false);
});
